/* Generated by Yosys 0.29+23 (git sha1 cdeef5481, gcc 7.5.0-3ubuntu1~18.04 -fPIC -Os) */

(* top =  1  *)
(* src = "rtl/fault_detection.v:1.1-42.10" *)
module fault_detection(clk, rst, ch1, ch2, ch3, ch4, fault, fault_code);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  (* src = "rtl/fault_detection.v:4.23-4.26" *)
  input ch1;
  wire ch1;
  (* src = "rtl/fault_detection.v:5.23-5.26" *)
  input ch2;
  wire ch2;
  (* src = "rtl/fault_detection.v:6.23-6.26" *)
  input ch3;
  wire ch3;
  (* src = "rtl/fault_detection.v:7.23-7.26" *)
  input ch4;
  wire ch4;
  (* src = "rtl/fault_detection.v:2.23-2.26" *)
  input clk;
  wire clk;
  (* src = "rtl/fault_detection.v:9.23-9.28" *)
  output fault;
  reg fault;
  (* src = "rtl/fault_detection.v:10.23-10.33" *)
  output [3:0] fault_code;
  reg [3:0] fault_code;
  (* src = "rtl/fault_detection.v:3.23-3.26" *)
  input rst;
  wire rst;
  assign _02_ = rst | ch1;
  assign _03_ = ch1 | ch2;
  assign _01_ = rst | _03_;
  assign _00_ = ch3 | _01_;
  assign _04_ = ch3 | ch4;
  assign _05_ = _03_ | _04_;
  (* src = "rtl/fault_detection.v:13.1-40.4" *)
  always @(posedge clk)
    if (rst) fault <= 1'h0;
    else fault <= _05_;
  (* src = "rtl/fault_detection.v:13.1-40.4" *)
  always @(posedge clk)
    if (_00_) fault_code[0] <= 1'h0;
    else fault_code[0] <= ch4;
  (* src = "rtl/fault_detection.v:13.1-40.4" *)
  always @(posedge clk)
    if (_01_) fault_code[1] <= 1'h0;
    else fault_code[1] <= ch3;
  (* src = "rtl/fault_detection.v:13.1-40.4" *)
  always @(posedge clk)
    if (_02_) fault_code[2] <= 1'h0;
    else fault_code[2] <= ch2;
  (* src = "rtl/fault_detection.v:13.1-40.4" *)
  always @(posedge clk)
    if (rst) fault_code[3] <= 1'h0;
    else fault_code[3] <= ch1;
endmodule
